---
kind: Pod
apiVersion: v1
metadata:
  name: efs-test-pod
  namespace: namespace
spec:
  containers:
  - name: efs-test-pod
    image: 152254703525.dkr.ecr.eu-west-1.amazonaws.com/enm/deployment-tests/busybox:1.24
    command:
    - "/bin/sh"
    args:
    - "-c"
    - touch /mnt/SUCCESS && echo "EFS test pod success" > /mnt/SUCCESS && cat /mnt/SUCCESS
      && exit 0 || exit 1
    volumeMounts:
    - name: efs-pvc
      mountPath: "/mnt"
  restartPolicy: Never
  volumes:
  - name: efs-pvc
    persistentVolumeClaim:
      claimName: efs
