---
apiVersion: batch/v1
kind: Job
metadata:
  name: elasticsearch-health-checker
  namespace: namespace
spec:
  template:
    spec:
      containers:
      - name: elasticsearch-checker
        image: 152254703525.dkr.ecr.eu-west-1.amazonaws.com/enm/deployment-tests/alpine:3.10
        command:
        - "/bin/sh"
        args:
        - "-c"
        - apk update && apk add --no-cache curl bash;
          echo "check cluster health";
          curl -sw '%{http_code}' http://elasticsearch/_cluster/health;
          echo -e "\ncreate an index";
          curl -sw '%{http_code}' -X PUT http://elasticsearch/test_doc/_doc/1 -H
          'Content-Type:application/json' -sw '%{http_code}' -d '{"test":"ENM"}';
          echo -e "\nget index";
          sleep 1;
          curl -sw '%{http_code}' -X GET -sw '%{http_code}' http://elasticsearch/test_doc/_search;
          echo -e "\ndelete index";
          curl -sw '%{http_code}' -X DELETE -sw '%{http_code}' http://elasticsearch/test_doc;
      restartPolicy: OnFailure
  backoffLimit: 4
